# Generated by Django 4.2.7 on 2023-12-17 05:09

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SolvedProblems",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "date",
                    models.DateField(
                        default=datetime.datetime(2023, 12, 17, 5, 9, 56, 113633)
                    ),
                ),
                ("time", models.DurationField()),
                (
                    "accuracy",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[django.core.validators.MaxValueValidator(100.0)],
                    ),
                ),
                (
                    "problemid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.apiproblems",
                    ),
                ),
                (
                    "userid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
