# Generated by Django 4.2.7 on 2023-12-17 05:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_solvedproblems"),
    ]

    operations = [
        migrations.AlterField(
            model_name="solvedproblems",
            name="date",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 12, 17, 5, 10, 48, 723010, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
