# Generated by Django 5.0 on 2023-12-22 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_solvedproblems_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solvedproblems',
            name='time',
            field=models.IntegerField(),
        ),
    ]
